namespace CosmosDB.Gremlin.Fluent.Functions
{
    public static class ExecutionProfileFunction
    {
        /// <summary>
        /// Creates a description of all operations generated by the executed Gremlin step
        /// </summary>
        /// <param name="builder"></param>
        /// <returns></returns>
        public static GremlinQueryBuilder ExecutionProfile(this GremlinQueryBuilder builder)
        {
            return builder.Add("executionProfile()");
        }
    }
}